### ISSUE TITLE
[bug] The forces value is missing from xServTopic output

### ISSUE THREAD

**Issue by ry0hei-kobayashi** [mcsix/xela_server_ros#3]
Hi, 
I have started service.launch, then I checked the xServTopic with rostopic echo. Taxels data appears fine, but forces data is missing. Please check the attached logs.
Do you have some solutions? Thanks．

OS: ubuntu20.04
Sensor: uSPa44 x2
Xela Software: V1.7.7 build 161703

``` -
    message: 253785
    time: 1738251542.227399
    model: "uSPa44"
    sensor_pos: 2
    taxels:
      -
        x: 33246
        y: 33253
        z: 37239
      -
        x: 32748
        y: 33288
        z: 37041
      -
        x: 32695
        y: 33296
        z: 37224
      -
        x: 32267
        y: 33219
        z: 37336
      -
        x: 33176
        y: 33047
        z: 37253
      -
        x: 32709
        y: 32755
        z: 36909
      -
        x: 32773
        y: 32888
        z: 36588
      -
        x: 32229
        y: 32827
        z: 37154
      -
        x: 33062
        y: 32819
        z: 37549
      -
        x: 32795
        y: 32945
        z: 37093
      -
        x: 32696
        y: 32783
        z: 36858
      -
        x: 32251
        y: 32843
        z: 37141
      -
        x: 33239
        y: 32467
        z: 37687
      -
        x: 32769
        y: 32449
        z: 37440
      -
        x: 32870
        y: 32389
        z: 37033
      -
        x: 32483
        y: 32426
        z: 37813
    forces: []
---
```

**Comment by mcsix** [comment]
Assuming from the empty forces element, my first assumption would be that in the xServ.ini file you have not set the `calibration = on` under `[sensor]` section. With all standard sensors, it is off by default and in case you run `xela_server` by itself, not through ROS, you can easily notice it in the terminal where all supported modules will be listed.
In case you are not sure, how to proceed, please submit your xServ.ini file (supposedly in /etc/xela directory).

Thank you

**Comment by ry0hei-kobayashi** [comment]
Thank you for your suggestion.
It's my ini file. 
```
[CAN]
bustype = socketcan
channel = can0
mode = 1 #periodic and on CAN message receive

[viz]
max_offset = 100
max_size = 100
arrows = off #use `half` or `full` to turn on
grid = on #use `off` to turn off
transparency = off #use `on` to turn on
origins = off #use `on` to turn on
fps = off #use `on` to show redraw rate of viz
ups = off #use `on` to show sensor update rate
temp_show = on #use `off` to disable temperature show (requires temperature enabled sensors to show up, otherwise hidden)
[debug]
sens_print = full

[sensor]
num_of_sensor = 2
version = 3          
model = uSPa44
[sensor1]
id = 1
module_name = on
rotation = 3 #-90 deg
[sensor2]
id = 2
module_name = on
rotation = 3 #-90 deg
```

**Comment by mcsix** [comment]
I see, please add the `calibration = on` to your INI file.
See the following section:
```ini
[sensor]
num_of_sensor = 2
version = 3          
model = uSPa44
calibration = on # this is needed for the forces
```

**Comment by ry0hei-kobayashi** [comment]
Thanks. It seems good.
I will close the issue.
Thank you for your help.

```
  -
    message: 12179
    time: 1738305361.6687307
    model: "uSPa44"
    sensor_pos: 2
    taxels:
      -
        x: 33256
        y: 33261
        z: 37227
      -
        x: 32740
        y: 33295
        z: 37019
      -
        x: 32690
        y: 33309
        z: 37216
      -
        x: 32259
        y: 33232
        z: 37335
      -
        x: 33174
        y: 33052
        z: 37229
      -
        x: 32697
        y: 32753
        z: 36902
      -
        x: 32769
        y: 32887
        z: 36564
      -
        x: 32205
        y: 32837
        z: 37148
      -
        x: 33061
        y: 32817
        z: 37551
      -
        x: 32790
        y: 32943
        z: 37083
      -
        x: 32691
        y: 32773
        z: 36839
      -
        x: 32227
        y: 32841
        z: 37128
      -
        x: 33247
        y: 32454
        z: 37678
      -
        x: 32771
        y: 32440
        z: 37438
      -
        x: 32873
        y: 32378
        z: 37016
      -
        x: 32463
        y: 32421
        z: 37824
    forces:
      -
        x: 0.0023114278446882963
        y: -0.0013132373569533229
        z: 0.009910198859870434
      -
        x: -0.003526564221829176
        y: 0.00016819262236822397
        z: 0.004775284789502621
      -
        x: -0.001953680766746402
        y: 0.0013787203934043646
        z: -0.0013695822563022375
      -
        x: 9.989505088014994e-06
        y: 0.00010738542914623395
        z: -0.0014853018801659346
      -
        x: 7.606121653225273e-05
        y: -0.0018123264890164137
        z: -0.00014965792070142925
      -
        x: 0.001031749416142702
        y: 0.00011351592547725886
        z: -0.013654527254402637
      -
        x: -0.0024740213993936777
        y: -0.00015261018415912986
        z: -0.008383817970752716
      -
        x: 0.00146570336073637
        y: 0.0009805046720430255
        z: 0.005713642109185457
      -
        x: -0.000656278629321605
        y: -0.0003262077225372195
        z: 0.007056650705635548
      -
        x: 0.0002938546531368047
        y: -0.0028427061624825
        z: 0.005145142320543528
      -
        x: 0.002407313324511051
        y: 0.00037450288073159754
        z: 0.02120286040008068
      -
        x: -0.0009169548284262419
        y: 0.00019892209093086421
        z: -0.0011911208275705576
      -
        x: 0.0010311162332072854
        y: -0.001027250080369413
        z: -0.001345682772807777
      -
        x: -0.0003166923706885427
        y: -4.123766484553926e-05
        z: -0.003806453198194504
      -
        x: -7.558259676443413e-05
        y: -6.672619201708585e-05
        z: -0.002377545228227973
      -
        x: 8.059437823249027e-05
        y: -0.0001415470032952726
        z: -0.008660022169351578
---

```
